### ISSUE TITLE
index incremental

### ISSUE THREAD

**Issue by AltiMario** [see-r/SeerDataCruncher#2]
An integer value can be an incremental index.
Check if the current value is biggest than the previous one.
![incremental_index](https://cloud.githubusercontent.com/assets/598726/11918528/540b72c4-a735-11e5-942d-577cdfb97206.png)

**Comment by AltiMario** [comment]
Because you are using the db to store the data, you can set the flag "index incremental" just if there is a "database for storing" already selected.
You should check this "flag" on front-end and prevent the error also on backend.

**Comment by AltiMario** [comment]
![incremental_bug](https://cloud.githubusercontent.com/assets/598726/12131989/afc6999c-b417-11e5-80a7-a6d286d675a2.png)

**Comment by mastrogiovanni** [comment]
Committed: waiting for Mario check

**Comment by AltiMario** [comment]
the logical check have to be applied also into backend
![only_one_index](https://cloud.githubusercontent.com/assets/598726/12566313/52f918d2-c3b9-11e5-9d34-a791c9e2f80f.png)
